### PR TITLE
Added getDistance() to btManifoldPoint

### PR DESCRIPTION
**Pull request by Bunzaga**
Added 'getDistance()' to the btManifoldPoint class, to get the distance between the shapes.

### CODE REVIEW

**Comment by kripken** [comment]
Hmm, is `Value` needed? `btScalar` is just a float or a double, so I think it should work without it.

**Comment by Bunzaga** [comment]
I wasn't sure, so I thought it would be better to be safe, than sorry :sweat_smile:  C++ isn't my native language, but I'm trying to contribute to the idl as I stumble my way through implementing Ammo.js.

**Comment by kripken** [comment]
Cool, thanks.

**Comment by kripken** [comment]
Merged.

**Pull request closed without merging**
