### PR TITLE
feat: GitHub CI

### PR DESCRIPTION
**Pull request by ianpurvis**

### CODE REVIEW

**Comment by ianpurvis** [comment]
@kripken I iterated on this in my fork and was able to get successful builds for ubuntu, Mac, and Windows. Feel free to test it out at https://github.com/ianpurvis/ammo.js/pull/3 and let me know what you think. I feel good about removing `make.py` with this in hand.

**Comment by kripken** [comment]
Looks good, thanks! Yes, I agree, we can remove `make.py` given we have CMake that is tested.

**Comment by kripken** [comment]
Do I need to do anything in this repo to enable the CI? Looks like actions are already enabled by default.

**Comment by ianpurvis** [comment]
Awesome... looks like it is working, I just created a new PR and the builds were triggered. 👍

**Pull request merged**
