### PR TITLE
Latest bullet3 submodule

### PR DESCRIPTION
**Pull request by Zentropivity**
So I added the latest version of bullet as submodule and added a bunch of newer features to the webidl binder.
There are few problems:

- The example `webgl_softbody_volume` does not work.
- Built file size is about 2x what it was before. (I think it can go 6x or more with all the stuff, but who needs it?)

This has all the features of the older version (and more), except:
- btDebugDrawer (Maybe I shouldn't have removed it...)
- `void setInternalTickCallback(VoidPtr cb, optional VoidPtr worldUserInfo, optional boolean isPreTick);` in `btDynamicsWorld`
That was removed to be able to use submodule. (Not sure if we needed it anyways...)

I totally forgot to run tests...

Haven't tested performance.
But examples run smooth when built Release.

There are still a lot of the bullet api missing but it comes down to personal needs, so everyone should modify their idl file to their taste, I think. (I am totally getting rid of RaycastVehicle in my version.)

### CODE REVIEW

**Comment by kripken** [comment]
Nice!

Is the 2x size increase with similar IDL files? Or is that because you wrapped more of the API?

Overall I'm not worried about build size much, as people should be customizing their own IDL files for their builds anyhow. But it would be nice to keep the default builds similar.

Next steps should probably include figuring out the failing stuff, and to get more people to test this.

**Comment by Zentropivity** [comment]
Most of the size increase came from not compiling with closure (oups) and there is some from wrapping more of the API.
With closure enabled the wasm version is about 1 MB less.

**Comment by Zentropivity** [comment]
As for why its failing... could it be that it does not git the submodule?
It says it cannot find the `CMakeLists.txt` in `ammo.js/bullet`.

**Comment by LeXXik** [comment]
Please, keep the `setInternalTickCallback`. PlayCanvas depends on it to fire kinematic vs non-dynamic rigidbodies collision events:
https://github.com/playcanvas/engine/blob/f140a24de070870d05354d6596e48184c76934bf/src/framework/components/rigid-body/system.js#L205

Also, the debug drawer is pretty useful to render the current state of the physics world. It saves a lot of time during the development:
https://playcanvas.com/project/744419/overview/ammo-debug-draw

**Comment by Zentropivity** [comment]
I see...
But I don't see a way to have `setInternalTickCallback` where it used to be on `btDynamicsWorld`.
That is due to not being able to bind to custom function pointers.

Since global functions also can not be bound, a compatibility struct could be added, like:
```
btCompat {
  setInternalTickCallback(btDynamicsWorld world, <the_parameters>)
}
```

**Comment by Zentropivity** [comment]
@LeXXik I made the changes. Do you think this will suffice?
By the way, the PlayCanvas graphics examples look really good.

**Comment by LeXXik** [comment]
Well, I am a consumer, so I don't really mind. It is probably up to @kripken. I think as long as the breaking change is documented, it should be fine. Perhaps @willeastcott from PlayCanvas may have an opinion.

**Comment by willeastcott** [comment]
Yeah, `setInternalTickCallback` is critical for PlayCanvas. From reading the thread, I'm not entirely clear on the meaning of this comment:

> That was removed to be able to use submodule.

I'm not familiar with the concept of submodules.

Essentially, the PlayCanvas run-time needs to be able to function correctly alongside any build of ammo. So currently, it does:

```javascript
            if (this.dynamicsWorld.setInternalTickCallback) {
                var checkForCollisionsPointer = Ammo.addFunction(this._checkForCollisions.bind(this), 'vif');
                this.dynamicsWorld.setInternalTickCallback(checkForCollisionsPointer);
            } else {
                // #if _DEBUG
                console.warn("WARNING: This version of ammo.js can potentially fail to report contacts. Please update it to the latest version.");
                // #endif
            }
```

If there's a way to update the code to also play nice with any changes proposed here, I think I'd be OK with that.

I'm also concerned about:

* Build size. The current build of ammo used by PlayCanvas devs is 258KB of WASM. This is fairly reasonable. There's not much scope for us to reduce this with a custom IDL because PlayCanvas devs might want to access any of the API and we don't want to limit that. End users could build their own version, but in practice. they don't bother.
* Performance. There was some benchmarking of an updated Bullet build of ammo previously and some significant slow downs were observed. Does this PR exhibit any performance differences versus the current head revision?

**Comment by Zentropivity** [comment]
By the submodule thing, I meant that we can not modify the source to add a Web IDL compatible function to bind on the class btDynamicsWorld.
So I added a class `btCompat` with the function `setInternalTickCallback` that takes a `btDynamicWorld` and the usual parameters.

About size... it looks a lot more than just 258KB... ~1-2MB
Performance, I haven't tested.

**Comment by willeastcott** [comment]
I should mention that it's 258KB GZIPped. :smile:

**Comment by lo-th** [comment]
problem's on softdemo is from softBodyHelpers.CreateFromTriMesh function 
this function call _free  on ? array maybe but is don't existe
_free work on vec3 transform quaternion ...

**Comment by lo-th** [comment]
i can say perf is good ; is start new version on ammo lab 
and is very  promising :)

**Comment by lo-th** [comment]
here the base preview in worker 
i have many option to add but is a good start 
i tell you if i find missing function other than Ammo.free and character

http://lo-th.github.io/root/ammo_next/index.html

**Comment by lo-th** [comment]
i find another problem sometime trimesh break engine without error ?

**Comment by lo-th** [comment]
yep problem's come from too many numstep ( i have to make some search )
btTriangleMesh work with index mesh or not is great ! 
let des = new Ammo.btTriangleMesh()
while( v--) des.findOrAddVertex( V ), false ) 
while( i--) des.addTriangleIndices( I1, I2, I3 ) ) 
or for unIndexed
while( v--) des.addTriangle( V1, V2, V3 ), false )

**Comment by lo-th** [comment]
Hi why you stop port ?
is working very well

**Comment by Zentropivity** [comment]
Hi, i closed it because I am busy with other stuff. I probably won't be working on this for now... Feel free to pick up where I left it.

**Comment by lo-th** [comment]
I understand, but it deserves a new branch,
I will soon update my engine and I must say that everything works perfectly with great stability

**Comment by max-sym** [comment]
What's the status of this? I think it would be super valuable to have the most recent pybullet in here since the current one is pretty outdated.

**Comment by max-sym** [comment]
Using it as a submodule is genius, I'm already trying to build it.
The only thing is that now the bullet3 is more up to date and we need to update `ammo.idl`. Do you have any suggestion on how to do that quicker if there's any way? How did you do it?

**Comment by max-sym** [comment]
Alright, thanks a lot for quick response! Let's see how it goes.

**Comment by max-sym** [comment]
@Zentropivity opened a new one ^.
The build worked. Thanks for laying the beginning for it!

**Comment by lo-th** [comment]
here you can test demo made with this version of ammo
https://lo-th.github.io/phy/index.html?E=w_ammo#start

**Pull request closed without merging**
