### PR TITLE
Fixed examples.

### PR DESCRIPTION
**Pull request by mrdoob**
Couldn't fix the wasm demo though.

#170

### CODE REVIEW

**Comment by mrdoob** [comment]
Seems like Atom did some space clean up.

This link should remove the noise:
https://github.com/kripken/ammo.js/pull/175/files?w=1

**Comment by kripken** [comment]
Thanks!

**Comment by mrdoob** [comment]
You may want to delete the `gh_pages` branch and change the setting of the repo so the GitHub Page is built out of `master`.

**Comment by mrdoob** [comment]
I can see you're currently copy-pasting the builds inside the `webgl_demo` though.

**Comment by kripken** [comment]
Yeah, good point. Done.

Sadly we still need to copy paste the wasm file for the wasm demo, no good way to load it from another directory yet.

**Comment by mrdoob** [comment]
> no good way to load it from another directory yet

Out of curiosity... Do you know if there are any plans on fixing that? workers/wasm side?

**Comment by kripken** [comment]
One option might be to embed the file, to work around this, https://github.com/kripken/emscripten/pull/5296 (but code size won't be great). Other options discussed here: https://github.com/kripken/emscripten/issues/5104

**Pull request merged**
