### PR TITLE
Add support for building with addFunction

### PR DESCRIPTION
**Pull request by kripken**
This does increase build size, so I think it should be off by default.

### CODE REVIEW

**Comment by MackeyK24** [comment]
Yo @kripken ... PR #251 Fixes these issues with OPTIONAL Add Function Support.

Please cancel PR #252 and use #251 instead

**Comment by MackeyK24** [comment]
Yo @kripken ... The build size increase is **MINOR** 

I think the PR #251 gives **Ammo.js** far better functionality and we be **closer** to the **Native Bullet Physics Engine** support.

**Comment by willeastcott** [comment]
When you say 'minor', can you what's the difference exactly? Numbers for GZIPed and not would be great.

**Comment by MackeyK24** [comment]
**Without closure option** ammo.js is about 2.1 MB

**With closure options** ammo.js is about 1.8 MB

Building on my mac pro.

Thats not bad for getting the **Native Bullet Physics Collision Contact Events**. Now can easily create **Unity Style** collision game mechanics code, creating functions like:

* OnCollisionEnter
* OnCollisionStay
* OnCollisionExit

And if supporting the CF_NO_CONTACT_RESPONSE collision flag

* OnTriggerEnter
* OnTriggerStay
* OnTriggerExit

From a Babylon Toolkit Framework point of view. That more that justifies all the **game mechanics** I can build with those collision contacts on the web... HEAH YEAH BRO :)

**Comment by evandarcy** [comment]
Does this PR allow for easier "exposing" of native Bullet functions when building Ammo.js?

**Comment by MackeyK24** [comment]
Yo @evandarcy ... It does for COLLISION CONTACT CALLBACK...

The **addFunction** support lets you use JavaScript to Wrap a JS Function with a Native Pointer for use with C++ code. Example:
```
var contactDestroyedCallbackPtr = Ammo.addFunction((userPersistentData) => {

    // Get both bodies from map using userPersistentData as the identifier and handle end events

    // Cleanup collision identifier body references on map to avoid collision contact memory leaks

});

var dynamicsWorld = new Ammo.btDiscreteDynamicsWorld(...);
dynamicsWorld.setContactDestroyedCallback(contactDestroyedCallbackPtr);
```

**Comment by kripken** [comment]
I think this PR is unneeded after we merged that other one.

**Pull request closed without merging**
