### PR TITLE
add Pointer_stringify to EXPORTED_RUNTIME_METHODS

### PR DESCRIPTION
**Pull request by InfiniteLee**
need Pointer_stringify to print out DOMStrings from `btIDebugDraw` `reportErrorWarning` and `draw3dText`.

### CODE REVIEW

**Comment by kripken** [comment]
Hmm, this will increase the build size noticeably. How about adding a mention to the README about this - may be a good idea to have a section about "reducing build size", where we can mention removing exported stuff, and also the option to remove stuff from the idl? lgtm with that.

**Comment by InfiniteLee** [comment]
I'd be ok with leaving it off by default if you're concerned about size. Right now you only need it if you get error messages when using the debugDraw. I can update AmmoDebugDrawer to check to see if that method is available and just print out a message of how to turn it on if it's not.

**Comment by InfiniteLee** [comment]
Something like:
```
...
  debug = 'debug' in sys.argv
  exported_runtime_methods = 'Pointer_stringify' if debug else '';
  args = '-O3 --llvm-lto 1 -s NO_EXIT_RUNTIME=1 -s NO_FILESYSTEM=1 -s EXPORTED_RUNTIME_METHODS=[' + exported_runtime_methods + ']'
...
```

**Comment by kripken** [comment]
Hmm, another build type seems excessive to me if it's just for this. I'd rather document this issue in the readme, that seems simpler.

**Pull request merged**
