### PR TITLE
Add btGImpactMeshShape interface

### PR DESCRIPTION
**Pull request by OliverXH**
Add btGImpactMeshShape interface, now multiple meshes can collide with each other.

### CODE REVIEW

**Comment by OliverXH** [comment]
[Example here](https://rawcdn.githack.com/OliverXH/ammo.js/7ebdb4b8fac56517c04fda2b6e1ebe03d54d6dec/examples/webgl_demo_gimpact_chain/index.html)

**Comment by kripken** [comment]
Thanks!

Did you make the new builds with closure compiler? Looking at them I think maybe not?

**Comment by OliverXH** [comment]
The new builds now have be built with closure compiler

**Review by kripken — APPROVED** [review]

**Comment by lo-th** [comment]
hi missing addTriangleIndices for index geometry 
but is maybe only on bullet 3.0

**Pull request merged**
