### PR TITLE
Adding setter and getter for SoftBody RestLengthScale.

### PR DESCRIPTION
**Pull request by Fowlet**
As titled. Tested and working.

### CODE REVIEW

**Review by kripken — COMMENTED** [review]
Thanks! Code looks good, but the JS builds are larger than expected. Maybe built without closure? (see https://github.com/kripken/ammo.js/#building )

**Comment by Fowlet** [comment]
Ah, I had built using the docker image, which runs:
```cmake -B builds && cmake --build builds```

Would it make sense for the docker command to instead be:
```cmake -B builds -DCLOSURE=1 && cmake --build builds``` ?

I can include the change to `docker-compose.yml` in this PR if you think building with closure is a sensible default.

**Comment by kripken** [comment]
Good point, yeah, please add that change - we should make optimal builds by default. Thanks!

**Comment by Fowlet** [comment]
Added the `docker-compose.yml` change and rebuilt `ammo.js` with closure. `ammo.js` seems smaller now. Force-pushed so that the old, large `ammo.js` doesn't stay in the git history for the repo.

**Review by kripken — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
