### PR TITLE
Terrain implementation

### PR DESCRIPTION
**Pull request by yomboprime**
#120 
Added btHeightfieldTerrainShape to the IDL.

Added also a demo under examples/webgl_demo_terrain/
It is a sine-wave terrain where different objects fall down.
You can rotate the camera by pressing left mouse button.

I hope the PR is all right, I'm still learning git.

### CODE REVIEW

**Comment by kripken** [comment]
I ran `python make.py` to build, then when I visit `examples/webgl_demo_terrain/index.html` I get `TypeError: Ammo.setValue is not a function     index.html:260:7`.

**Comment by yomboprime** [comment]
It's strange that the ```setValue``` function is undefined. It is described [in the emscripten API here.](https://kripken.github.io/emscripten-site/docs/api_reference/preamble.js.html?highlight=setvalue#setValue)
For me it works perfectly. Why could it be undefined for you? I'm compiling in Linux Debian, latest Emscripten 1.35.8

I use the function to set the values of the heightfield, contained in a float array.

**Comment by kripken** [comment]
Ok, I see - `setValue` used to be exported by default, but we no longer do, to reduce build size. Also it is better to directly write to memory, for efficiency. I made that change and now it works, merged. Thanks!

**Comment by yomboprime** [comment]
Thanks!
> Also it is better to directly write to memory, for efficiency.

How is that done?

**Comment by kripken** [comment]
See https://github.com/kripken/ammo.js/commit/91cbb79fb190b85caf4167740a7f2fd7b71fe876 , basically emscripten provides the typed array views, and you can write to them. `HEAPF32` is a view of 32-bit floats, etc. The only tricky bit is remembering the `>>2` for 4-byte data, and so forth.

**Comment by yomboprime** [comment]
Ah! I see now, thanks.

BTW, I'm planning more additions...

**Comment by kripken** [comment]
Great :)

**Pull request merged**
