### PR TITLE
Update ammo.idl - getOverlappingPairCache

### PR DESCRIPTION
**Pull request by MackeyK24**
Add getOverlappingPairCache to btAxisSweep interface

### CODE REVIEW

**Comment by kripken** [comment]
I think that method is defined in the .h on the parent `btBroadphaseInterface`, so it could be there?

**Comment by MackeyK24** [comment]
Nope ... you need it on btAxisSweep3

**Comment by MackeyK24** [comment]
you need it for this type call
```
this.m_overlappingPairCache.getOverlappingPairCache().setInternalGhostPairCallback(new Ammo.btGhostPairCallback());
```

Example Usage:
```
const worldMin:any = Ammo.btVector3(-1000,-1000,-1000);
const worldMax:any = Ammo.btVector3(1000,1000,1000);
this.m_overlappingPairCache = new Ammo.btAxisSweep3(worldMin, worldMax);

const collisionShape:any = this._abstractMesh.physicsImpostor.physicsBody.getCollisionShape();
const startTransform:any = new Ammo.btTransform();
startTransform.setIdentity();
startTransform.setOrigin(new Ammo.btVector3(0.0, 0.0, 0.0));

this.m_ghostObject = new Ammo.btPairCachingGhostObject();
this.m_ghostObject.setWorldTransform(startTransform);
this.m_overlappingPairCache.getOverlappingPairCache().setInternalGhostPairCallback(new Ammo.btGhostPairCallback());

this.m_ghostObject.setCollisionShape(collisionShape);
this.m_ghostObject.setCollisionFlags(BABYLON.CollisionFlags.CF_CHARACTER_OBJECT);

const stepHeight:number = 0.35;
this.m_character = new Ammo.btKinematicCharacterController(this.m_ghostObject, collisionShape, stepHeight);

// Static Collisions
var world = BABYLON.SceneManager.GetPhysicsWorld(this.scene);
//world.addCollisionObject(this.m_ghostObject, BABYLON.CollisionFilterGroups.CharacterFilter, BABYLON.CollisionFilterGroups.StaticFilter | BABYLON.CollisionFilterGroups.DefaultFilter);
world.addCollisionObject(this.m_ghostObject, BABYLON.CollisionFilterGroups.CharacterFilter, BABYLON.CollisionFilterGroups.AllFilter);
world.addAction(this.m_character);
```

**Comment by MackeyK24** [comment]
Note: Im using it in my forked build and it works great :)

**Comment by MackeyK24** [comment]
I think your right... Its on both the broadphase interface and the axis sweep... We should just put them on both :)

**Comment by MackeyK24** [comment]
Now you can call getOverlappingPairCache() from the **world.getBroadphase()** or directly from the **btAxisSweep3** used for pair cache.

That should cover all the bases :)

**Comment by MackeyK24** [comment]
Yo @kripken ... Whats the verdict... I can work with just the **btBroadphaseInterface**

But just so you know... that function exists in **btAxisSweep3**

Let me know and i will remove **btAxisSweep3** and i can always use **world.getBroadphase()** to execute **getOverlappingPairCache()**

But we **at least** need it in **btBroadphaseInterface** because that the main and easiest way to access the global broadphase for the world.

**Comment by MackeyK24** [comment]
OK bro... Its just on **btBroadphaseInterface**

Can please take a look at committing :)

**Comment by kripken** [comment]
Great, thanks @MackeyK24! (And sorry for the delay, been very busy...)

**Pull request merged**
