### PR TITLE
fix: Ammo() should assign the loaded module to global Ammo

### LINKED ISSUE #323: New cmake build system removed addFunction support
I was export addFunction using make.py

```
  if add_function_support:
    args += ' -s RESERVED_FUNCTION_POINTERS=20 -s EXTRA_EXPORTED_RUNTIME_METHODS=["addFunction"]'
```

So i can do stuff like
```
                    const contactAddedCallbackPtr = Ammo.addFunction((cp:any, colObj0Wrap:any, partId0:number, index0:number, colObj1Wrap, partId1:number, index1:number) => {
                        // NOTE: KEEP FOR REFERENCE
                        // colObj0Wrap = Ammo.wrapPointer(colObj0Wrap, Ammo.btCollisionObjectWrapper);
                        // colObj1Wrap = Ammo.wrapPointer(colObj1Wrap, Ammo.btCollisionObjectWrapper);
                        // const colobj0:any = colObj0Wrap.getCollisionObject();
                        // const colobj1:any = colObj1Wrap.getCollisionObject();
                        // if (colobj0 != null && colobj1 != null) {
                        //    const colshape0:any = colobj0.getCollisionShape();
                        //    const colshape1:any = colobj1.getCollisionShape();
                        // }
                        if (physicsplugin.world.adjustInternalEdgeContacts) {
                            physicsplugin.world.adjustInternalEdgeContacts(cp, colObj1Wrap, colObj0Wrap, partId1, index1);
                            return true;
                        } else {
                            return false;
                        }
                    });
```

Now with the new cmake -B builds ... it does not support 

```
$ cmake -B builds -DRESERVED_FUNCTION_POINTERS=20 -DEXTRA_EXPORTED_RUNTIME_METHODS=["addFunction"] -DTOTAL_MEMORY=134217728

```

So how am i supposed to get Ammo.addFunction back ???

### PR DESCRIPTION
**Pull request by ianpurvis**
Fixes #323

### CODE REVIEW

**Comment by kripken** [comment]
How did tests pass without this?

**Comment by ianpurvis** [comment]
The tests create a local `const Ammo` within the scope of the test block:

https://github.com/kripken/ammo.js/blob/69d961fffd3b0dba53ae9da8f8ff3e23c910d77d/tests/basics.js#L4-L5

 In the case of the hello world test, we explicitly defined `global.Ammo` for the dynamic function 

https://github.com/kripken/ammo.js/blob/69d961fffd3b0dba53ae9da8f8ff3e23c910d77d/tests/hello-world.js#L9-L11

**Comment by ianpurvis** [comment]
Maybe it's better not to mix the global and local approach... should I eliminate local `Ammo` across the test suite?

```js
const test = require('ava');
const loadAmmo = require('./helpers/load-ammo.js');

test('basics', async t => {
  await loadAmmo()
```

Unfortunately using the name `Ammo` does not work-

```js
const test = require('ava');
const Ammo = require('./helpers/load-ammo.js');

test('basics', async t => {
  await Ammo()
```

**Comment by kripken** [comment]
Optimally we'd test something as close as possible to how users use the code. But I'm actually not sure what the most common pattern is. So I guess I don't have strong feelings either way here.

**Comment by ianpurvis** [comment]
Should we go ahead and merge as-is to fix the regression? With the additional test, I think we'll get decent coverage for both usage patterns.

**Pull request merged**
