### PR TITLE
feat: Softbody Faces

### PR DESCRIPTION
**Pull request by ianpurvis**
Adds interfaces for soft body faces.

### CODE REVIEW

**Comment by ianpurvis** [comment]
Sorry- I somehow opened this on the main repo and not my fork. Is it useful? I can close or if there is interest, I can spend some time testing with spidermonkey and the webgl demo.

**Comment by kripken** [comment]
Definitely useful! Additions to the idl file are always good.

If you want to update the builds that's good too, but make sure to build them with latest emscripten and with closure compiler.

**Comment by ianpurvis** [comment]
@kripken I had some trouble building, but was able to fix it in #311. So that Makefile was used to do these builds. I ran the test suite and spent some time running the webgl examples as well.

**Comment by kripken** [comment]
Thanks!

**Pull request merged**
