### PR TITLE
Update the btContactSolverInfo to allow get/set of m_numIterations

### PR DESCRIPTION
**Pull request by beiller**
For constraint GOODNESS. Had to set getSolverInfo to [Ref] otherwise it seemed to have no effect (first time with emscripten)

Now my constraints aren't so droopy!

### CODE REVIEW

**Comment by kripken** [comment]
Did you get a compile error without that Value=>Ref change?

**Comment by beiller** [comment]
Nope I have compiled and tested (only tests with my own development but it
seems fine). I didn't want to push my build, but I could if that is helpful.

**Comment by kripken** [comment]
Oh I see now, yeah, Ref is needed so updates to it modify the object.

**Comment by kripken** [comment]
Thanks!

**Pull request merged**
