### PR TITLE
Add collision object to convex sweep test result

### PR DESCRIPTION
**Pull request by LeXXik**
The change allows to access the object that was hit during the convex sweep test.

### CODE REVIEW

**Comment by ianpurvis** [comment]
Nice! Sorry for the delay... we have been fixing the CI builds.

**Comment by ianpurvis** [comment]
@LeXXik If you have a minute, could you rebase this off master to gain the build fixes?

**Comment by LeXXik** [comment]
Rebased.

**Comment by ianpurvis** [comment]
Looks like the commit history got weird. Let me try resetting the base branch to see if it will clean it up at all

**Comment by ianpurvis** [comment]
@kripken Do you think a squash merge would resolve the duplicated commits here? Although the PR diff shows 6 files changed, when I diff `LeXXik:master` on the command line I get the patch from 2bfc6e0

**Comment by ianpurvis** [comment]
Nice, that would be the best- thanks!

**Comment by kripken** [comment]
(In general squash merges sound fine to me.)

**Pull request closed without merging**
