### PR TITLE
Additional SoftBody functions

### PR DESCRIPTION
**Pull request by donalffons**
Added addForce/addAeroForceToNode to btSoftBody; Added m_f and m_v to Node

### CODE REVIEW

**Comment by donalffons** [comment]
Oh, damn. Sorry for committing so many files. I only meant to commit the ammo.idl and the 3 build files. Hope this still works for you - if not, I will create a new pull request.

**Comment by kripken** [comment]
Hmm yeah, something seems wrong with all those files. You don't need another PR though, you can force-push (with `-f`) to this branch on the remote, and add a comment (force-pushes don't notify people that the PR changed).

**Comment by donalffons** [comment]
OK, I'll give it a try :)

**Comment by donalffons** [comment]
OK, this took me a couple of tries. But I think I got it now. Thanks for the tutorial ;-). And let me know if it's alright now!

**Comment by donalffons** [comment]
One more thing: There are some concerns about increased file sizes with Ammo.JS versions from my (and other people's) setup [here](https://github.com/armory3d/haxebullet/pull/17). Maybe I'm missing some optimizations? It would be greatly appreciated if you could recompile the builds to keep the file size small.

**Comment by kripken** [comment]
Thanks!

Looking into the code size issues now.

**Comment by kripken** [comment]
I think the code size difference was due to building with or without closure (190K vs 160K). I pushed builds with closure now, and updated the docs.

**Comment by donalffons** [comment]
Thank you!

**Pull request merged**
