### PR TITLE
fix worker.js import scripts, it should be ammo.js

### PR DESCRIPTION
**Pull request by JayceLai**

### CODE REVIEW

**Comment by kripken** [comment]
We call the wasm version `ammo.wasm.js` currently, see https://github.com/kripken/ammo.js/tree/master/builds

**Comment by kripken** [comment]
Was this not working somewhere online? Perhaps we uploaded just the js and not the wasm version?

**Comment by JayceLai** [comment]
> We call the wasm version `ammo.wasm.js` currently, see https://github.com/kripken/ammo.js/tree/master/builds

I noticed that there have two example but both import wasm version, is it right?

image

**Comment by kripken** [comment]
Oh, right, thanks @JayceLai! Yeah, only one should be the wasm version.

**Pull request merged**
